"""empty message

Revision ID: 37e0d953f539
Revises: 6f35cf7636e9
Create Date: 2017-11-25 12:35:26.704003

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '37e0d953f539'
down_revision = '6f35cf7636e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('p1_scores_strs', sa.String(length=1024), nullable=True))
    op.add_column('room', sa.Column('p2_scores_strs', sa.String(length=1024), nullable=True))
    op.add_column('room', sa.Column('scores_strs', sa.String(length=1024), nullable=True))
    op.drop_column('room', 'p1_scores')
    op.drop_column('room', 'p2_scores')
    op.drop_column('room', 'scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('scores', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('p2_scores', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('p1_scores', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('room', 'scores_strs')
    op.drop_column('room', 'p2_scores_strs')
    op.drop_column('room', 'p1_scores_strs')
    # ### end Alembic commands ###
