"""empty message

Revision ID: 569a6a4735f6
Revises: 37e0d953f539
Create Date: 2017-11-29 23:41:26.824157

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '569a6a4735f6'
down_revision = '37e0d953f539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('next_game_bool', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'next_game_bool')
    # ### end Alembic commands ###
