"""empty message

Revision ID: 65859b19facc
Revises: 037359269124
Create Date: 2017-11-30 02:09:31.577469

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '65859b19facc'
down_revision = '037359269124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'dropout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('dropout', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
