"""empty message

Revision ID: 6f35cf7636e9
Revises: b87f672cb9b5
Create Date: 2017-11-24 23:33:47.292554

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6f35cf7636e9'
down_revision = 'b87f672cb9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move', sa.Column('is_observable', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('experimental_condition', sa.String(length=512), nullable=True))
    op.add_column('room', sa.Column('p1_is_observable', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('p2_is_observable', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('scores', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'scores')
    op.drop_column('room', 'score')
    op.drop_column('room', 'p2_is_observable')
    op.drop_column('room', 'p1_is_observable')
    op.drop_column('room', 'experimental_condition')
    op.drop_column('move', 'is_observable')
    # ### end Alembic commands ###
