"""empty message

Revision ID: b87f672cb9b5
Revises: 4b741bebfebd
Create Date: 2017-11-23 15:45:53.078292

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b87f672cb9b5'
down_revision = '4b741bebfebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('p1_score', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('p2_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'p2_score')
    op.drop_column('room', 'p1_score')
    # ### end Alembic commands ###
