"""empty message

Revision ID: cb2c7f3dece0
Revises: 
Create Date: 2017-11-22 13:23:13.598372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2c7f3dece0'
down_revision = '3975622d1054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'last_active')
    # ### end Alembic commands ###
